export function generateReportText({ fileName, analysis, stats, keywords }) {
  const lines = []

  lines.push('RESUME ANALYSIS REPORT')
  lines.push('Generated by Resume Analyzer & ATS Score Checker')
  lines.push(`File: ${fileName}`)
  lines.push(`Date: ${new Date().toLocaleString()}`)
  lines.push('')
  lines.push(`ATS Score: ${analysis.score}/100 (${analysis.category})`)
  lines.push('')
  lines.push('Score Breakdown')
  lines.push(`Skills Match: ${analysis.breakdown.skills}/25`)
  lines.push(`Contact Info: ${analysis.breakdown.contact}/10`)
  lines.push(`Skills Section: ${analysis.breakdown.skillsSection}/5`)
  lines.push(`Education: ${analysis.breakdown.education}/10`)
  lines.push(`Projects: ${analysis.breakdown.projects}/15`)
  lines.push(`Experience: ${analysis.breakdown.experience}/20`)
  lines.push(`Certifications: ${analysis.breakdown.certifications}/5`)
  lines.push(`Resume Length: ${analysis.breakdown.length}/10`)
  lines.push('')
  lines.push('Resume Statistics')
  lines.push(`Word Count: ${stats.wordCount}`)
  lines.push(`Character Count: ${stats.charCount}`)
  lines.push(`Skill Match Rate: ${stats.skillMatchPercent}%`)
  lines.push('')
  lines.push(`Found Skills: ${keywords.found.join(', ') || 'None'}`)
  lines.push(`Missing Skills: ${keywords.missing.join(', ') || 'None'}`)

  return lines.join('\n')
}

export function downloadTextFile(content, fileName) {
  const blob = new Blob([content], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = fileName
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}
